export const products_json = [
  {
    id: "pkprod001",
    name: "Serum Cấp Ẩm Hằng Ngày",
    slug: "serum-cap-am-hang-ngay",
    sku: "HA-SRM-001",
    price: 350000,
    compareAtPrice: 420000,
    stock: 120,
    imageUrl: "https://picsum.photos/seed/serum/800/600",
    images: [
      {
        url: "https://picsum.photos/seed/serum/800/600",
        alt: "Serum cấp ẩm - ảnh 1",
      },
      {
        url: "https://picsum.photos/seed/serum2/800/600",
        alt: "Serum cấp ẩm - ảnh 2",
      },
    ],
    shortDescription: "Serum HA thấm nhanh, cấp ẩm sâu cho da căng mướt.",
    description:
      "Công thức Hyaluronic Acid đa trọng lượng phân tử giúp giữ ẩm bền vững, phục hồi màng ẩm nhanh chóng.",
    ingredients:
      "Aqua, Glycerin, Sodium Hyaluronate (HA), Panthenol, Allantoin.",
    usage: "Dùng sáng/tối sau bước làm sạch và toner. 2–3 giọt cho toàn mặt.",
    volume: "30",
    volumeUnit: "ml",
    origin: "Italy",
    isFeatured: true,
    status: "PUBLISHED",
    publishedAt: "2025-08-20T04:00:00.000Z",
    metaTitle: "Serum Cấp Ẩm Hằng Ngày - HATHI",
    metaDescription:
      "Serum HA cấp ẩm sâu, phục hồi màng ẩm, cho làn da căng mướt rạng rỡ.",
    brandId: null,
    categoryId: "ckcat001",
    createdAt: "2025-09-04T10:00:00.000Z",
    updatedAt: "2025-09-04T10:00:00.000Z",
  },
  {
    id: "pkprod002",
    name: "Sữa Rửa Mặt Dịu Nhẹ",
    slug: "sua-rua-mat-diu-nhe",
    sku: "CL-WS-002",
    price: 220000,
    compareAtPrice: null,
    stock: 300,
    imageUrl: "https://picsum.photos/seed/cleanser/800/600",
    images: [
      {
        url: "https://picsum.photos/seed/cleanser/800/600",
        alt: "Sữa rửa mặt dịu nhẹ - ảnh 1",
      },
    ],
    shortDescription: "Làm sạch êm, không khô căng, phù hợp da nhạy cảm.",
    description:
      "pH 5.5 cân bằng, loại bỏ bụi bẩn và dầu thừa mà không phá vỡ hàng rào bảo vệ da.",
    ingredients: "Aqua, Coco-Glucoside, Betaine, Panthenol.",
    usage: "Làm ướt mặt, tạo bọt và massage 30–45 giây, rửa sạch.",
    volume: "150",
    volumeUnit: "ml",
    origin: "Italy",
    isFeatured: false,
    status: "PUBLISHED",
    publishedAt: "2025-08-22T04:00:00.000Z",
    metaTitle: "Sữa Rửa Mặt Dịu Nhẹ - HATHI",
    metaDescription: "Sữa rửa mặt pH 5.5 dịu nhẹ, sạch mà vẫn mềm mịn.",
    brandId: null,
    categoryId: "ckcat001",
    createdAt: "2025-09-04T10:00:00.000Z",
    updatedAt: "2025-09-04T10:00:00.000Z",
  },
  {
    id: "pkprod003",
    name: "Kem Dưỡng Ẩm 24h",
    slug: "kem-duong-am-24h",
    sku: "MOIST-003",
    price: 420000,
    compareAtPrice: 480000,
    stock: 80,
    imageUrl: "https://picsum.photos/seed/moist/800/600",
    images: [
      {
        url: "https://picsum.photos/seed/moist/800/600",
        alt: "Kem dưỡng ẩm - ảnh 1",
      },
      {
        url: "https://picsum.photos/seed/moist2/800/600",
        alt: "Kem dưỡng ẩm - ảnh 2",
      },
    ],
    shortDescription: "Dưỡng ẩm bền bỉ, khóa ẩm qua đêm.",
    description:
      "Ceramide + Squalane nuôi dưỡng hàng rào bảo vệ da, duy trì độ ẩm đến 24h.",
    ingredients: "Aqua, Ceramide NP, Squalane, Shea Butter.",
    usage: "Thoa cuối quy trình, sáng và tối.",
    volume: "50",
    volumeUnit: "ml",
    origin: "Italy",
    isFeatured: true,
    status: "PUBLISHED",
    publishedAt: "2025-08-25T04:00:00.000Z",
    metaTitle: "Kem Dưỡng Ẩm 24h - HATHI",
    metaDescription:
      "Ceramide & Squalane khóa ẩm, phục hồi da mềm mịn suốt ngày dài.",
    brandId: null,
    categoryId: "ckcat001",
    createdAt: "2025-09-04T10:00:00.000Z",
    updatedAt: "2025-09-04T10:00:00.000Z",
  },
  {
    id: "pkprod004",
    name: "Kem Chống Nắng SPF50 PA++++",
    slug: "kem-chong-nang-spf50",
    sku: "SUN-004",
    price: 360000,
    compareAtPrice: null,
    stock: 200,
    imageUrl: "https://picsum.photos/seed/sunscreen/800/600",
    images: [
      {
        url: "https://picsum.photos/seed/sunscreen/800/600",
        alt: "Kem chống nắng - ảnh 1",
      },
    ],
    shortDescription: "Chất gel thoáng nhẹ, bảo vệ UVA/UVB.",
    description:
      "Không để lại vệt trắng, kiểm soát dầu nhẹ, phù hợp khí hậu nóng ẩm.",
    ingredients: "Uvinul A Plus, Tinosorb S, Vitamin E.",
    usage: "Dùng sau dưỡng, trước trang điểm. Thoa lại sau 2–3 giờ.",
    volume: "50",
    volumeUnit: "ml",
    origin: "Italy",
    isFeatured: true,
    status: "PUBLISHED",
    publishedAt: "2025-08-18T04:00:00.000Z",
    metaTitle: "Kem Chống Nắng SPF50 PA++++ - HATHI",
    metaDescription: "Bảo vệ toàn diện, thấm nhanh, không bết dính.",
    brandId: null,
    categoryId: "ckcat007",
    createdAt: "2025-09-04T10:00:00.000Z",
    updatedAt: "2025-09-04T10:00:00.000Z",
  },
  {
    id: "pkprod005",
    name: "Mặt Nạ Phục Hồi",
    slug: "mat-na-phuc-hoi",
    sku: "MASK-005",
    price: 280000,
    compareAtPrice: 320000,
    stock: 150,
    imageUrl: "https://picsum.photos/seed/mask/800/600",
    images: [
      {
        url: "https://picsum.photos/seed/mask/800/600",
        alt: "Mặt nạ phục hồi - ảnh 1",
      },
    ],
    shortDescription: "Làm dịu tức thì, phục hồi da sau nắng.",
    description: "Chiết xuất lô hội & panthenol làm dịu, cấp ẩm mạnh mẽ.",
    ingredients: "Aloe Vera, Panthenol, Allantoin.",
    usage: "Đắp 10–15 phút, 2–3 lần/tuần.",
    volume: "25",
    volumeUnit: "ml",
    origin: "Italy",
    isFeatured: false,
    status: "PUBLISHED",
    publishedAt: "2025-08-12T04:00:00.000Z",
    metaTitle: "Mặt Nạ Phục Hồi - HATHI",
    metaDescription: "Mặt nạ làm dịu, cấp ẩm cho làn da nhạy cảm.",
    brandId: null,
    categoryId: "ckcat008",
    createdAt: "2025-09-04T10:00:00.000Z",
    updatedAt: "2025-09-04T10:00:00.000Z",
  },
  {
    id: "pkprod006",
    name: "Body Lotion Dưỡng Thể",
    slug: "body-lotion-duong-the",
    sku: "BODY-006",
    price: 260000,
    compareAtPrice: null,
    stock: 90,
    imageUrl: "https://picsum.photos/seed/bodylotion/800/600",
    images: [
      {
        url: "https://picsum.photos/seed/bodylotion/800/600",
        alt: "Body lotion - ảnh 1",
      },
    ],
    shortDescription: "Dưỡng mềm mịn, thơm dịu, thấm nhanh.",
    description: "Bơ hạt mỡ và vitamin E khóa ẩm, cải thiện độ đàn hồi.",
    ingredients: "Shea Butter, Vitamin E, Glycerin.",
    usage: "Thoa sau khi tắm, tập trung vùng khô.",
    volume: "250",
    volumeUnit: "ml",
    origin: "Italy",
    isFeatured: false,
    status: "PUBLISHED",
    publishedAt: "2025-08-10T04:00:00.000Z",
    metaTitle: "Body Lotion Dưỡng Thể - HATHI",
    metaDescription: "Dưỡng thể mềm mịn, hương thơm dễ chịu.",
    brandId: null,
    categoryId: "ckcat006",
    createdAt: "2025-09-04T10:00:00.000Z",
    updatedAt: "2025-09-04T10:00:00.000Z",
  },
];
